/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shenghangao_filterit_MainActivity_amplitudeSeekBar */

#ifndef _Included_com_shenghangao_filterit_MainActivity_amplitudeSeekBar
#define _Included_com_shenghangao_filterit_MainActivity_amplitudeSeekBar
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
