/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shenghangao_filterit_MainActivity_waveChange */

#ifndef _Included_com_shenghangao_filterit_MainActivity_waveChange
#define _Included_com_shenghangao_filterit_MainActivity_waveChange
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
